version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cat_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  pgdata:
